name: Probar Funciones
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar compilador de C
      uses: actions/setup-cmake@v1

    - name: Compilar test_functions.c
      run: gcc -o result test_functions.c

    - name: Ejecutar resultado
      run: ./result
